### ISSUE TITLE
列多的时候，横向滚动条和宽度一样长，虽然能滚动

### ISSUE THREAD

**Issue by xijinhua** [kohaiy/easytable#1]
![image](https://github.com/kohaiy/easytable/assets/14870095/2b417a46-3148-4230-a56b-c0db813bbad2)

**Comment by kohaiy** [comment]
是不想要横行滚动条吗，可以提供下示例代码吗？

**Comment by xijinhua** [comment]
找到问题了，和我的样式有点冲突，谢谢！
