### ISSUE TITLE
打包后的文件，类型依然异常

### ISSUE THREAD

**Issue by woodcoal** [kohaiy/easytable#11]
虽然 0.0.5 修复了部分类型文件，但是深层文件依然错误

![image](https://github.com/kohaiy/easytable/assets/70026047/5955cb1a-9add-4097-b0af-b7a23690875b)

路径不对

![image](https://github.com/kohaiy/easytable/assets/70026047/8671ac31-fd52-4fed-84c5-b8610ff5fbd9)

**Comment by kohaiy** [comment]
在 0.0.6 fixed 了
