### ISSUE TITLE
表头能否自定义，例如使用html代码，或者改变表头的字体颜色或者背景颜色

### ISSUE THREAD

**Issue by CupOfBread** [kohaiy/easytable#13]
表头能否自定义，例如使用html代码，或者改变表头的字体颜色或者背景颜色。希望能加一个这个功能

**Comment by kohaiy** [comment]
renderHeaderCell 这个支持自定义表头的内容，
参考这里：
https://kohaiy.github.io/easytable/#/zh/doc/table/cell-custom?anchor=header+%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8D%95%E5%85%83%E6%A0%BC

表头背景颜色通过给格子加类名来修改样式，可以看这里：
https://kohaiy.github.io/easytable/#/zh/doc/table/cell-style?anchor=%E8%A1%A8%E5%A4%B4%E5%8D%95%E5%85%83%E6%A0%BC%E6%A0%B7%E5%BC%8F
