### ISSUE TITLE
npm 包少了文件

### ISSUE THREAD

**Issue by woodcoal** [kohaiy/easytable#6]
![image](https://github.com/kohaiy/easytable/assets/70026047/63cee935-f194-427b-84be-b2375f0d2557)

```
import VeLocale from './packages/ve-locale';
```

`ve-locale` 没有打包进去，TS 找不到类型

**Comment by kohaiy** [comment]
需要这样去引入：

```js
import { VeLocale } from "@easytable/vue";
import zhCN from "@easytable/vue/libs/locale/lang/zh-CN.js";
VeLocale.use(zhCN); 
```

**Comment by woodcoal** [comment]
> 需要这样去引入：
> 
> ```js
> import { VeLocale } from "@easytable/vue";
> import zhCN from "@easytable/vue/libs/locale/lang/zh-CN.js";
> VeLocale.use(zhCN); 
> ```

是这么操作的，编辑器提示 VeLocale 找不到类型，点击到类型定义会提示具体错误：

![image](https://github.com/kohaiy/easytable/assets/70026047/6d89790e-677e-4283-b9c7-8d18cc5c6b95)

语言也提示找不到类型声明

![image](https://github.com/kohaiy/easytable/assets/70026047/f2f06caf-532e-4038-94f9-bcfb8a60bc5d)

并不说不能用，只是出现 ts 类型报错。
